### ISSUE TITLE
api errors

### ISSUE THREAD

**Issue by vreshch** [garage-it/SmartHouse-frontend#103]
Frontend does not handle server errors 
e.g.  when /api/dashboard return null - console erorrs apeared

**Comment by borys-ihnatyev** [comment]
Maybe we should add toaster library and show toast on such error ?
https://www.npmjs.com/package/angular2-toaster
https://www.npmjs.com/package/ng2-toastr

**Comment by velmyk** [comment]
If it wont take mach time I will do in scope of this issue

**Comment by velmyk** [comment]
Issue fixed on back-end
